name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Shellcheck
        run: shellcheck bin/*

      - name: Test Plugin
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: "lane --version"
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
